// <auto-generated />
namespace CarShowroom.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _500char : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_500char));
        
        string IMigrationMetadata.Id
        {
            get { return "202108241204443_500char"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
